### ISSUE TITLE
UVs formula?

### ISSUE THREAD

**Issue by makc** [mganeko/THETA_GL#1]
What's the formula for UVs you used? Can't find it anywhere.

**Comment by mganeko** [comment]
I do not use any formula to make UVs.

UV was made by Unity. 
- Japanese language blog post: http://tips.hecomi.com/entry/2015/10/11/211456

Then I use Brender to adujst UV and convert to json.
- Japanese language blog post: https://lab.infocom.co.jp/2016/01/theta-s-2-uv.html

Today Ricoh Cloud API beta has streaming sample with UV formula.
I recommend to use it.
https://github.com/ricohapi/video-streaming-sample-app/blob/master/samples/common/thetaview.js

**Comment by makc** [comment]
thank you for the link. it seems to remove some artifacts around the seam at the cost of simply removing the area. yours:

![screen shot 2016-09-17 at 14 52 49](https://cloud.githubusercontent.com/assets/242577/18608322/a95b708a-7ce6-11e6-9a85-07afcf525d5d.png)

theirs:

![screen shot 2016-09-17 at 14 50 28](https://cloud.githubusercontent.com/assets/242577/18608326/b952b098-7ce6-11e6-815c-dcd458c0abd0.png)

**Comment by mganeko** [comment]
Thanks for comparing.
I am closing this issue.
